experiment_config:
  experiment_name: question-answer-test
  chat_model: false
  n_tokens: 5
  tokenizer_pretrained_model_name_or_path: Meta-Llama-3-8B
  pretrained_model_name_or_path: Meta-Llama-3-8B
  checkpoints_folder: /home/paperspace/Projects/posteriors/examples/bayes_llama3/logs/ensemble_bayes/usable_checkpoints
