logs_dir: "./experiments/TQA"
dataset_path: 
  - "/home/paperspace/Projects/posteriors/datasets/tqa_train_val_test/test/tqa_v2_test.json"
  - /home/paperspace/Projects/posteriors/datasets/tqa_train_val_test/train/tqa_v1_train.json

# Experiment
experiment_config:
  experiment_name: question-answer-test
  chat_model: false
  n_tokens: 10
  tokenizer_pretrained_model_name_or_path: Meta-Llama-3-8B-Instruct
  pretrained_model_name_or_path: Meta-Llama-3-8B-Instruct
  checkpoints_folder: /home/paperspace/Projects/posteriors/examples/bayes_llama3/logs/bayes_instruct_no_temp/usable_checkpoints
