seed: 2024
epochs: 10

learning_rate: 1e-3
alpha: 1e-2
beta: 0.0
momenta: 0.0
set_temperature: False

metrics_log_frequency: 5
save_frequency: 300

num_workers: 8
batch_size: 10

data_dir: "/home/paperspace/Projects/posteriors/datasets/tqa_train_val_test"