seed: 2024
epochs: 10

learning_rate: 1e-2
alpha: 1e-2
beta: 0.0
momenta: 0.0

metrics_log_frequency: 10
save_frequency: 100

num_workers: 8
batch_size: 10

data_dir: "/home/paperspace/Projects/posteriors/datasets/tqa_train_val_test"