seed: 2024
weight_decay: 0.1
learning_rate: 1e-4
epochs: 10

log_frequency: 10
metrics_log_frequency: 10
save_frequency: 100

num_workers: 8
batch_size: 2

data_dir: "/home/paperspace/Projects/posteriors/datasets/tqa_train_val_test"

tokenizer_model: "Llama-2-7b/tokenizer.model"
