logs_dir: "./experiments"
dataset_path:
  head_qa:
    - /home/paperspace/Projects/posteriors/datasets/head_qa/data/HEAD/test_HEAD.json
    # - /home/paperspace/Projects/posteriors/datasets/head_qa/data/HEAD/train_HEAD.json
  tqa:
    - /home/paperspace/Projects/posteriors/datasets/tqa_train_val_test/test/tqa_v2_test.json
    # - /home/paperspace/Projects/posteriors/datasets/tqa_train_val_test/train/tqa_v1_train.json

# Experiment
experiment_config:
  experiment_name: question-answer-test
  chat_model: false
  n_tokens: 5
  tokenizer_pretrained_model_name_or_path: Meta-Llama-3-8B
  pretrained_model_name_or_path: Meta-Llama-3-8B
  checkpoints_folder: /home/paperspace/Projects/posteriors/examples/bayes_llama3/logs/ensemble_bayes/usable_checkpoints
