logs_dir: "./experiments/TQA"
dataset_path:
  tqa:
    - /home/paperspace/Projects/posteriors/datasets/tqa_train_val_test/test/tqa_v2_test.json
    - /home/paperspace/Projects/posteriors/datasets/tqa_train_val_test/train/tqa_v1_train.json
  head_qa:
    - /home/paperspace/Projects/posteriors/datasets/head_qa/data/HEAD/test_HEAD.json
    - /home/paperspace/Projects/posteriors/datasets/head_qa/data/HEAD/train_HEAD.json

# Experiment
experiment_config:
  eval_pretrained_model: true
  experiment_name: question-answer-test
  chat_model: false
  n_tokens: 5
  tokenizer_pretrained_model_name_or_path: Meta-Llama-3-8B-Instruct
  pretrained_model_name_or_path: Meta-Llama-3-8B-Instruct
